#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
function src_optional {
  if [[ -s "$1" ]]; then
    source $1
  fi
}

export EDITOR=vim
export BUNDLE_EDITOR=$EDITOR

export GIT_EDITOR=$EDITOR
export TERM=xterm-256color
export GREP_OPTIONS='--color=auto'
export HISTCONTROL='ignorespace'

if [[ "$(docker-machine status dev)" == 'Running' ]]; then
  eval "$(docker-machine env dev)"
  export REDIS_HOST="$(docker-machine ip dev)"
fi

if which jenv > /dev/null; then eval "$(jenv init -)"; fi

alias h="cd ~/Documents/projects/$@"

src_optional "${ZDOTDIR:-$HOME}/.specific_confs.sh"

bindkey "^R" history-incremental-search-backward
bindkey "^F" history-incremental-search-forward

export CDPATH="$CDPATH:.:$HOME/Documents/projects"

source /usr/local/opt/chruby/share/chruby/chruby.sh
