#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
function src_optional {
  if [[ -s "$1" ]]; then
    source $1
  fi
}

export EDITOR=vim
export BUNDLE_EDITOR=$EDITOR

export GIT_EDITOR=$EDITOR
export GIT_COMMITTER_EMAIL='narciso.benigno@gmail.com'
export GIT_AUTHOR_EMAIL='narciso.benigno@gmail.com'
export TERM=xterm-256color
export GREP_OPTIONS='--color=auto'

if [ "$(boot2docker status)" != "running" ]; then
  echo "Starting boot2docker (It will be done once time)"
  boot2docker up
fi
`boot2docker shellinit`

alias h="cd ~/Documents/projects/$@"

src_optional "${ZDOTDIR:-$HOME}/.specific_confs.sh"

bindkey "^R" history-incremental-search-backward
bindkey "^F" history-incremental-search-forward
