#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
function src_optional {
  if [[ -s "$1" ]]; then
    source $1
  fi
}

export EDITOR=vim
export BUNDLE_EDITOR=$EDITOR

unset GREP_OPTIONS

export GIT_EDITOR=$EDITOR
export TERM=xterm-256color
export HISTCONTROL='ignorespace'

if which jenv > /dev/null; then eval "$(jenv init -)"; fi

alias h="cd ~/Documents/projects/$@"

src_optional "${ZDOTDIR:-$HOME}/.specific_confs.sh"

bindkey "^R" history-incremental-search-backward
bindkey "^F" history-incremental-search-forward

export CDPATH="$CDPATH:.:$HOME/Documents/projects"

chruby_path='/usr/share/chruby/chruby.sh'
if [[ `uname` == 'Darwin' ]]; then
	chruby_path=/usr/local/opt/chruby/share/chruby/chruby.sh
fi

source $chruby_path

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/narciso2b/.sdkman"
[[ -s "/home/narciso2b/.sdkman/bin/sdkman-init.sh" ]] && source "/home/narciso2b/.sdkman/bin/sdkman-init.sh"
